### ISSUE TITLE
Double point moved to end of line in subs.wanted

### ISSUE THREAD

**Issue by Yveske82** [ebergama/sonarr-sub-downloader#8]
I have this problem that at some point in my subs.wanted file most of or all double points are move to the end of the line. I guess this happens when the subs.wanted file is updated.
So as example instead of it having it look like this:
`/mnt/2tb/Media/Series/Legion/Season 02/Legion - S02E02 - Chapter 10.mkv:/mnt/2tb/Media/Series/Legion/Season 02/Legion - S02E02 - Chapter 10.en.srt`
It looks like this:
`/mnt/2tb/Media/Series/Legion/Season 02/Legion - S02E02 - Chapter 10.mkv /mnt/2tb/Media/Series/Legion/Season 02/Legion - S02E02 - Chapter 10.en.srt  :`

This is the error I get in my mail:
`Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1064, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1396, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1681, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1365, in full_process_value
    value = self.process_value(ctx, value)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1355, in process_value
    return self.type_cast_value(ctx, value)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1344, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1343, in _convert
    return tuple(_convert(x, level - 1) for x in value or ())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1343, in <genexpr>
    return tuple(_convert(x, level - 1) for x in value or ())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1342, in _convert
    return self.type(value, self, ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/types.py", line 38, in __call__
    return self.convert(value, param, ctx)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 173, in convert
    return Language.fromietf(value)
  File "/usr/local/lib/python2.7/dist-packages/babelfish/language.py", line 126, in fromietf
    language = cls(language_subtag)
  File "/usr/local/lib/python2.7/dist-packages/babelfish/language.py", line 82, in __init__
    raise ValueError('%r is not a valid language' % language)
ValueError: u'/mnt/2tb/media/series/the last man on earth/season 04/the last man on earth ' is not a valid language`

**Comment by faulander** [comment]
same happens to me, must be an error in the  search-wanted.sh script.
It works, as longs as the subs.wanted is written by  sub-downloader.sh - when it's written bei search-wanted.sh it gets corrupted.

**Comment by Yveske82** [comment]
For a moment I suspected it maybe had something to do with the locale settings so I changed from en_gb.utf-8 to c.utf-8 and for a moment I had the impression it worked but then it just started again. Like @faulander says, it must be something with the search-wanted.sh script.

**Comment by Yveske82** [comment]
@faulander in your search-wanted.sh can you on the last line replace 
`echo -en $MISSED > $WANTED_FILE` 
with
`echo -en "$MISSED" > "$WANTED_FILE"`
So put double quotes around $MISSED and $WANED_FILE
Been using it a week now and it seems to be working so if you could test it as well.

**Comment by Yveske82** [comment]
@ebergama this seems to fix the problem. Can you maybe update the script?
